spring.application.name=football

# Настройки подключения к PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sportpark
spring.datasource.username=postgres
spring.datasource.password=0A1n2t3o4n5!

# Настройки JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Настройки Liquibase (Управление схемами)
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true